# Generated by Django 4.2.4 on 2024-03-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
